language: node_js
node_js:
  - '5'
  - '4'
script: npm test
after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
before_deploy: npm install -g grunt-cli && grunt
deploy:
  provider: releases
  api_key:
    secure: BuwI6ZTmF1jqRS1Eml/zUEwd5yCsdL6R2DBN2MaCZa+uftXm1tgsmWX+Js2hPv7w6iA9Ekx0gLgok0yn6rjZGodIqraRRE+jD6IC7WSa+Ix2JrYudqVePoiPcM+ODfYZMLLwz7tL2urJH8PzTBuiXyUbY3YWJdHXqSMO8OEo/dPcfI3S4dUUvB9MUxG8jtnq/G1COuHp1JkAZOURLQNkb3uiOTm+kVQYtSmHTJMG4IoB9fJsd5CRmFISTtaphXEWVyE9ZpLU5W3K1LL3a9caza3//jTfbepyCeoYVXVONtpC7wH6zd80/3WhIkCsdYFzSoIz/uKYzGhR6PmtzDPysr1kprYZL37fjAmey+HxIbxIvv84tgtYYWIAnodu7oH+4MPocjnpGhuMJnw0pu1oWJf3jsaRbg7Z7D4WXmCCiAK6CtZvNc+183d1BDb/aNTlSXZpQEM0EfHFdV8J/Cy7EAB9jOhjQov1WO9UvrKCmqdKmX020ijZ5C1LfkyRwqJXmdSxbhV/0Zl2sQnJso/FfUf8I83AANx0yCvyUiBH48WuFojPwtYLQXaJTllKOU+CCfgsebwmg2UEwmeWbf2XnsMj6Ed6s/37UF9HDQMnoTWv0RbPgU+NYR9/tgt8GjrZTpdFbXdtuNXdrNEgf8NmhOr2ZYEiqpx6hKvMGXvIaAk=
  file:
    - dist/j29n.js
    - dist/j29n.min.js
  skip_cleanup: true
  on:
    tags: true
addons:
  code_climate:
    repo_token: 0392217b68c4b09602e084d4ece9a6ea0d090069aaa3f8b3f0e388d0a3c86f4d
